version: '3.8'

services:
  neo4j:
    image: neo4j:latest  # Use Neo4j latest image for compatibility
    container_name: neo4j-apoc
    environment:
      NEO4J_AUTH: "neo4j/Test@12345"  # Set your username and password
      NEO4J_apoc_export_file_enabled: "true"  # Enable APOC file export
      NEO4J_apoc_import_file_enabled: "true"  # Enable APOC file import
      NEO4J_apoc_import_file_use__neo4j__config: "true"  # Use Neo4j config for file import paths
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"  # Enable unrestricted APOC procedures
      NEO4J_dbms_security_procedures_allowlist: "apoc.meta.*,apoc.schema.*"  # Allow specific APOC procedures
      NEO4J_PLUGINS: '["apoc"]'  # Specify APOC plugin
    ports:
      - "7474:7474"  # HTTP Neo4j port
      - "7687:7687"  # Bolt port for Neo4j
    volumes:
      - ./data:/data  # Persist data on host machine
      - ./logs:/logs  # Persist logs on host machine
      - ./import:/import  # For importing data to Neo4j
      - ./plugins:/plugins  # Plugin directory
    restart: unless-stopped
